<a href="https://colab.research.google.com/github/minonza/NLP/blob/main/NLP2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Word Embedding_1, count vectorizaation BOW, n-gram***

*machine learning models do not understand any string or word it understands number. we willuse technique which will convert the text into number.

this number is called vector*


high level word embedding



**BOW** model is used in NLP to represent the given text/sentence/document without giving any importance to grammer or occurance order of the words.

--> it keeps count of frequency of the words in the text document.

ex: my name is mini sharma. my father is a manager.
I:2 is:2, father:1



drawback: gives more importance to stopwords.  to resove this Tf-idf was introduced.

**n-gram** keeps context of text intact. N-gram is sequence of words from a given text document. unlike bow method.. which only cares about frequency and doesnt care about grammer.

n=1 unigram

n=2 bigram

n=3 trigram and so n.

example: I went for a cup of coffee but i ended up having lunch with her.

unigram: i,went,to,have,a,cup,of,coffee......

bigram, i went, to have, a cup ,.....

trigram, i went to, a cup of, coffee and ended,.....

bow method is nothing but n-gram n=1

**skip grams:** words not necessary be in the same order some words can be skipped.
example: i dont understand what is the problem here.

1 skip 2 grams: i understand, dont what , understand is, what the , is problem, the here.

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.corpus import stopwords
import pandas as pd
string=["This is an example of bag of words!"] #single document ("," seperates each document)
vect1=CountVectorizer() #converts text into tokens
vect1.fit_transform(string)
print("bag of words",vect1.get_feature_names())

bag of words ['an', 'bag', 'example', 'is', 'of', 'this', 'words']


In [6]:
vect1.vocabulary_

{'an': 0, 'bag': 1, 'example': 2, 'is': 3, 'of': 4, 'this': 5, 'words': 6}

In [7]:
#fit and transform to check if the word is present or not
c_vect=CountVectorizer()
c_vect.fit(string)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [9]:
string2=['Lets understand is of word is']
c_new_vect=c_vect.transform(string2)
print("text present at",c_new_vect.toarray())
#compare with indexes
print("original indexes",vect1.get_feature_names()) #occurance of is and of

text present at [[0 0 0 2 1 0 0]]
original indexes ['an', 'bag', 'example', 'is', 'of', 'this', 'words']


In [12]:
##bag of words using stopwords (you can avoid writing extra steps to remove stopwords)
import nltk
nltk.download('stopwords')
stopwords=stopwords.words('english')
string=["This is an example of bag of words"]
vect1=CountVectorizer(stop_words=stopwords)
print(vect1)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None,
                stop_words=['i', 'me', 'my', 'myself', 'we', 'our', 'ours',
                            'ourselves', 'you', "you're", "you've", "you'll",
                            "you'd", 'your', 'yours', 'yourself', 'yourselves',
                            'he', 'him', 'his', 'himself', 'she', "she's",
                            'her', 'hers', 'herself', 'it', "it's", 'its',
                            'itself', ...],
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)


In [13]:
vect1.fit_transform(string)
print("bag of words:",vect1.get_feature_names())
print("vocab           :vect1.vocabulary_")#printing only important words except stop words

bag of words: ['bag', 'example', 'words']
vocab           :vect1.vocabulary_


In [16]:
def text_matrix(message, countvect):
  terms_doc=countvect.fit_transform(message)
  return pd.DataFrame(terms_doc.toarray(),columns=countvect.get_feature_names())


In [17]:
message=['A message is a discrete unit of communication intended by the source for consumption by some recipient or group of recipients.']
c_vect=CountVectorizer()
print("below matyrix is bag of words approach")
text_matrix(message,c_vect)

below matyrix is bag of words approach


by  communication  consumption  discrete  ...  some  source  the  unit
0   2              1            1         1  ...     1       1    1     1

[1 rows x 17 columns]

In [22]:
#n-grams
from sklearn.feature_extraction.text import CountVectorizer

from nltk.tokenize import word_tokenize
string=["This is an exmaple of gram!"]
vect1=CountVectorizer(ngram_range=(1,1))

vect1.fit_transform(string)

vect2=CountVectorizer(ngram_range=(2,2))

vect2.fit_transform(string)

vect3=CountVectorizer(ngram_range=(3,3))

vect3.fit_transform(string)

vect4=CountVectorizer(ngram_range=(4,4))

vect4.fit_transform(string)

print("1-gram:",vect1.get_feature_names())
print("2-gram:",vect2.get_feature_names())
print("3-gram:",vect3.get_feature_names())
print("4-gram:",vect4.get_feature_names())








1-gram: ['an', 'exmaple', 'gram', 'is', 'of', 'this']
2-gram: ['an exmaple', 'exmaple of', 'is an', 'of gram', 'this is']
3-gram: ['an exmaple of', 'exmaple of gram', 'is an exmaple', 'this is an']
4-gram: ['an exmaple of gram', 'is an exmaple of', 'this is an exmaple']


***tf-idf --> Term frequency-inverse document frequency***
reflects how import is a word to a document in a collection of corpus.

**term frequency = (number of times word appears in document)/(total number of words in the document)**


-disadvantage of term frequency is that gives higher weight to words with higher frequency.


***Inverse document frequency*** = log[(Number of document)/(number of documents the word appears in)]

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
tfid=TfidfVectorizer(smooth_idf=False)
doc=["This is an example","we will see how it works","IDF can be confusing"]
doc_vector=tfid.fit_transform(doc)
df=pd.DataFrame(doc_vector.todense(),columns=tfid.get_feature_names())
df

an   be  can  confusing  ...  this        we      will     works
0  0.5  0.0  0.0        0.0  ...   0.5  0.000000  0.000000  0.000000
1  0.0  0.0  0.0        0.0  ...   0.0  0.408248  0.408248  0.408248
2  0.0  0.5  0.5        0.5  ...   0.0  0.000000  0.000000  0.000000

[3 rows x 14 columns]

In [25]:
def text_matrix(message,countvect):
  terms_doc=countvect.fit_transform(message)
  return pd.DataFrame(terms_doc.toarray(),columns=countvect.get_feature_names())
  

In [26]:
feb_message=["Who is that covid covid",
             "covid is nothing",
             "covid cases are dropping"]
tf=TfidfVectorizer()
text_matrix(feb_message,tf)
             

are     cases     covid  ...   nothing      that       who
0  0.000000  0.000000  0.592567  ...  0.000000  0.501651  0.501651
1  0.000000  0.000000  0.425441  ...  0.720333  0.000000  0.000000
2  0.546454  0.546454  0.322745  ...  0.000000  0.000000  0.000000

[3 rows x 8 columns]

In [28]:
jul_message=["what is that covid covid",
             "covid is bad"]
text_matrix(jul_message,tf)

bad     covid        is      that      what
0  0.000000  0.668501  0.334251  0.469778  0.469778
1  0.704909  0.501549  0.501549  0.000000  0.000000

**Countvectorizer,TF-IDF,n-grams**

In [29]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
arr=['car was cleaned by jack','jack was cleaned by car.']

In [30]:
vectorizer=CountVectorizer(ngram_range=(2,2))
X=vectorizer.fit_transform(arr)
print("feature names \n",vectorizer.get_feature_names())
print("Array \n",X.toarray())

feature names 
 ['by car', 'by jack', 'car was', 'cleaned by', 'jack was', 'was cleaned']
Array 
 [[0 1 1 1 0 1]
 [1 0 0 1 1 1]]


In [32]:
vectorizer=TfidfVectorizer(ngram_range=(2,2))
X=vectorizer.fit_transform(arr)
print(X.toarray())

[[0.         0.57615236 0.57615236 0.40993715 0.         0.40993715]
 [0.57615236 0.         0.         0.40993715 0.57615236 0.40993715]]


**Word2Vec**

in one hot encoding  1. have a good day 2. have a great day


they both have same encoding thats why we use word2vec.



In [34]:
import re
import nltk
from gensim.models import Word2Vec
from nltk.corpus import stopwords
import matplotlib.pyplot as plt
%matplotlib inline


In [44]:
"""Coronavirus disease (COVID-19) is an infectious disease caused by a newly discovered coronavirus.

Most people infected with the COVID-19 virus will experience mild to moderate respiratory illness and recover without requiring special treatment.  Older people, and those with underlying medical problems like cardiovascular disease, diabetes, chronic respiratory disease, and cancer are more likely to develop serious illness.

The best way to prevent and slow down transmission is to be well informed about the COVID-19 virus, the disease it causes and how it spreads. Protect yourself and others from infection by washing your hands or using an alcohol based rub frequently and not touching your face. 

The COVID-19 virus spreads primarily through droplets of saliva or discharge from the nose when an infected person coughs or sneezes, so it’s important that you also practice respiratory etiquette (for example, by coughing into a flexed elbow)."""

'Coronavirus disease (COVID-19) is an infectious disease caused by a newly discovered coronavirus.\n\nMost people infected with the COVID-19 virus will experience mild to moderate respiratory illness and recover without requiring special treatment.  Older people, and those with underlying medical problems like cardiovascular disease, diabetes, chronic respiratory disease, and cancer are more likely to develop serious illness.\n\nThe best way to prevent and slow down transmission is to be well informed about the COVID-19 virus, the disease it causes and how it spreads. Protect yourself and others from infection by washing your hands or using an alcohol based rub frequently and not touching your face. \n\nThe COVID-19 virus spreads primarily through droplets of saliva or discharge from the nose when an infected person coughs or sneezes, so it’s important that you also practice respiratory etiquette (for example, by coughing into a flexed elbow).'

In [45]:

paragraph = paragraph.translate(str.maketrans('','',string.punctuation))
text=re.sub(r'\[[0-9]*\]','',paragraph)
text=re.sub(r'\s+','',text)
text=text.lower()
text=re.sub(r'\d','',text)
text=re.sub(r'\s+','',text)




AttributeError: ignored